# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'import.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class _Import(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.setupUi()

    def setupUi(self):
        self.setObjectName("Import")
        self.resize(425, 424)
        self.horizontalLayout = QtWidgets.QHBoxLayout(self)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self)
        self.widget.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: 2px solid white;\n"
"    border-radius: 5px;\n"
"    color: white;\n"
"}\n"
"#chosen {\n"
"    color: white;\n"
"}\n"
"\n"
"#chosen::hover {\n"
"    color: rgb(221, 221, 221)\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color: rgb(120, 54, 120);\n"
"}\n"
"\n"
"QComboBox {\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    border: 2px solid rgb(230, 230, 230);\n"
"    border-radius: 5px\n"
"}\n"
"\n"
"QComboBox::hover {\n"
"    border: 3px solid rgb(120, 54, 120);\n"
"}\n"
"\n"
"QLineEdit#password {\n"
"    background-color: transparent;\n"
"    border-radius: 5px;\n"
"    color: white;\n"
"    border: 2px solid white\n"
"}\n"
"\n"
"QLineEdit#password::focus {\n"
"    border-color: rgb(120, 54, 120);\n"
"}")
        self.widget.setObjectName("widget")
        self.back = QtWidgets.QPushButton(self.widget)
        self.back.setGeometry(QtCore.QRect(0, 0, 71, 41))
        self.back.setMinimumSize(QtCore.QSize(40, 30))
        self.back.setMaximumSize(QtCore.QSize(16777215, 100000))
        self.back.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("graphic/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back.setIcon(icon)
        self.back.setIconSize(QtCore.QSize(30, 30))
        self.back.setObjectName("back")
        self.way = QtWidgets.QComboBox(self.widget)
        self.way.setGeometry(QtCore.QRect(90, 70, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.way.setFont(font)
        self.way.setMaxVisibleItems(2)
        self.way.setObjectName("way")
        self.way.addItem("")
        self.way.addItem("")
        self.password = QtWidgets.QLineEdit(self.widget)
        self.password.setGeometry(QtCore.QRect(20, 130, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.password.setFont(font)
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.browse = QtWidgets.QPushButton(self.widget)
        self.browse.setGeometry(QtCore.QRect(20, 200, 101, 41))
        self.browse.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        self.browse.setFont(font)
        self.browse.setObjectName("browse")
        self._import = QtWidgets.QPushButton(self.widget)
        self._import.setGeometry(QtCore.QRect(130, 300, 131, 41))
        self._import.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        self._import.setFont(font)
        self._import.setObjectName("_import")
        self.chosen = QtWidgets.QLabel(self.widget)
        self.chosen.setGeometry(QtCore.QRect(140, 200, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.chosen.setFont(font)
        self.chosen.setObjectName("chosen")
        self.horizontalLayout.addWidget(self.widget)

        self.browse.hide()
        self.chosen.hide()

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Import", "Import"))
        self.way.setItemText(0, _translate("Import", "Private Key"))
        self.way.setItemText(1, _translate("Import", "JSON File"))
        self.password.setPlaceholderText(_translate("Import", "Paste your private key string here"))
        self.browse.setText(_translate("Import", "Choose File"))
        self._import.setText(_translate("Import", "Import"))
        self.chosen.setText(_translate("Import", "No file chosen"))
