# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addToken.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class AddToken(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.setupUi()

    def setupUi(self):
        self.setObjectName("addToken")
        self.resize(427, 439)
        self.horizontalLayout = QtWidgets.QHBoxLayout(self)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self)
        self.widget.setStyleSheet(
            """
            QLineEdit, #tokenAddress, #abi {
                background-color: transparent;
                border: 3px solid white;
                border-radius: 5px;
                color: white;
                font: 75 12pt "Myanmar Text";
                height: 25px
                }
            
            QLineEdit::disabled {
                background-color: rgb(125, 50, 105)
                }

            QLineEdit::focus, #abi::focus {
                border-color:rgb(209, 99, 209)
                }

            QPushButton {
                color: white;
                background-color: #B154B1;
                border: 1px solid rgb(197, 93, 197);
                border-radius: 5px
                }

            QPushButton::disabled {
                background-color: #CA8ACA;
                }

            QPushButton::pressed{
                border-color: white
                }
                """
                )

        self.widget.setObjectName("widget")
        self.layoutWidget = QtWidgets.QWidget(self.widget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 0, 391, 321))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tokenAddress = QtWidgets.QLineEdit(self.layoutWidget)
        self.tokenAddress.setObjectName("tokenAddress")
        self.verticalLayout.addWidget(self.tokenAddress)
        self.abi = QtWidgets.QTextEdit(self.layoutWidget)
        self.abi.setObjectName("abi")
        self.verticalLayout.addWidget(self.abi)
        self.layoutWidget1 = QtWidgets.QWidget(self.widget)
        self.layoutWidget1.setGeometry(QtCore.QRect(200, 340, 201, 51))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cancel = QtWidgets.QPushButton(self.layoutWidget1)
        self.cancel.setMinimumSize(QtCore.QSize(0, 25))
        self.cancel.setObjectName("cancel")
        self.horizontalLayout_2.addWidget(self.cancel)
        self.add = QtWidgets.QPushButton(self.layoutWidget1)
        self.add.setEnabled(False)
        self.add.setMinimumSize(QtCore.QSize(0, 25))
        self.add.setObjectName("add")
        self.horizontalLayout_2.addWidget(self.add)
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("addToken", "addToken"))
        self.tokenAddress.setPlaceholderText(_translate("addToken", "Token Contract Address"))
        self.cancel.setText(_translate("addToken", "Cancel"))
        self.add.setText(_translate("addToken", "Add"))
