# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'logIn.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class LogIn(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.setupUi()
        
    def setupUi(self):
        self.setObjectName("LogIn")
        self.resize(429, 433)
        self.horizontalLayout = QtWidgets.QHBoxLayout(self)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self)
        self.frame.setStyleSheet("QFrame#titleBar {\n"
"    border-bottom: 3px solid white;\n"
"    background-color: rgb(161, 76, 161);\n"
"}\n"
"QLabel#logo, QLabel#appLogo {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QLabel#title, QLabel#appName {\n"
"    background-color: transparent;\n"
"    color: black;\n"
"    font: 75 20pt \"Nirmala UI\";\n"
"}\n"
"\n"
"QLabel#title::hover, QLabel#appName::hover {\n"
"    color: rgb(53, 53, 53)\n"
"}\n"
"\n"
"QPushButton#close {\n"
"    background-color:  rgb(161, 76, 161);\n"
"    color: red;\n"
"    border: 4px solid white;\n"
"    border-left: 0;\n"
"    border-top: 0;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton#minimize {\n"
"    background-color:  rgb(161, 76, 161);\n"
"    color: green;\n"
"    border: 4px solid white;\n"
"    border-left: 0;\n"
"    border-top: 0;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton#minimize::pressed, QPushButton#close::pressed {\n"
"    background-color: rgb(149, 70, 149);\n"
"    border: 4px solid rgb(229, 229, 229);\n"
"    border-bottom: 0;\n"
"    border-right: 0\n"
"}\n"
"\n"
"#password {\n"
"    color: white;\n"
"    border: 3px solid white;\n"
"    border-radius: 5px\n"
"}\n"
"\n"
"QLineEdit#password::focus {\n"
"    border-color: #CA8ACA\n"
"}\n"
"\n"
"QPushButton#submit {\n"
"    color: white;\n"
"    border: 3px solid #592859;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton#submit::pressed {\n"
"    border-color: rgb(124, 56, 124);\n"
"    background-color: rgb(145, 69, 145);\n"
"    padding-top: 10px;\n"
"    padding-left: 10px\n"
"}\n"
"\n"
"QPushButton#restore {\n"
"    background-color: transparent;\n"
"    color: rgb(6, 255, 118)\n"
"}\n"
"QPushButton#restore::hover {\n"
"    color: rgb(5, 229, 102)\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.appLogo = QtWidgets.QLabel(self.frame)
        self.appLogo.setGeometry(QtCore.QRect(130, 20, 161, 91))
        self.appLogo.setText("")
        self.appLogo.setPixmap(QtGui.QPixmap("graphic/logo.png"))
        self.appLogo.setScaledContents(True)
        self.appLogo.setObjectName("appLogo")
        self.appName = QtWidgets.QLabel(self.frame)
        self.appName.setGeometry(QtCore.QRect(140, 130, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.appName.setFont(font)
        self.appName.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.appName.setObjectName("appName")
        self.password = QtWidgets.QLineEdit(self.frame)
        self.password.setGeometry(QtCore.QRect(20, 190, 371, 41))
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(17)
        self.password.setFont(font)
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.submit = QtWidgets.QPushButton(self.frame)
        self.submit.setGeometry(QtCore.QRect(110, 260, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.submit.setFont(font)
        self.submit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.submit.setObjectName("submit")
        self.restore = QtWidgets.QPushButton(self.frame)
        self.restore.setGeometry(QtCore.QRect(40, 330, 331, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.restore.setFont(font)
        self.restore.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.restore.setObjectName("restore")
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, ):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("LogIn", "LogIn"))
        self.appName.setText(_translate("LogIn", "Zahir Wallet"))
        self.password.setPlaceholderText(_translate("LogIn", "Enter password"))
        self.submit.setText(_translate("LogIn", "Log In"))
        self.restore.setText(_translate("LogIn", "Restore from seed phrase"))
