# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Main(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.setupUi()
        
    def setupUi(self):
        self.setObjectName("main")
        self.resize(424, 431)
        self.verticalLayout = QtWidgets.QVBoxLayout(self)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self)
        self.frame.setStyleSheet("QFrame#account_options {\n"
"    background-color: rgb(148, 67, 148);\n"
"    border: 3px solid white;\n"
"    border-radius: 5px\n"
"}\n"
"\n"
"QLabel, #accounts {\n"
"    color: white;\n"
"    \n"
"    font: 75 16pt \"Myanmar Text\";\n"
"}\n"
"\n"
"QLabel::hover, #accounts {\n"
"    color: rgb(234, 234, 234)\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: transparent\n"
"}\n"
"\n"
"QPushButton#_import, QPushButton#send, QPushButton#create {\n"
"    border: 3px solid white;\n"
"    color: black;\n"
"    border-radius: 5px;\n"
"    font: 75 10pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton#_import::hover, QPushButton#send::hover, QPushButton#create::hover {\n"
"    background-color: rgb(141, 63, 141)\n"
"}\n"
"\n"
"QPushButton#_import::pressed, QPushButton#send::pressed, QPushButton#create::pressed {\n"
"    background-color: rgb(130, 58, 130);\n"
"    padding-left: 3px;\n"
"    padding-top: 3px\n"
"}\n"
"\n"
"QTabBar:tab {\n"
"    width: 198px;\n"
"    height: 20px;\n"
"    padding-bottom: 5px;\n"
"    color: white;\n"
"    font: 75 14pt \"Urdu Typesetting\";\n"
"}\n"
"\n"
"QTabBar:tab:!selected {\n"
"    border: 3px solid black;\n"
"    border-bottom: 0;\n"
"    border-radius: 5px;\n"
"    background-color: rgb(165, 78, 165)\n"
"}\n"
"\n"
"QTabBar:tab:!selected::hover {\n"
"    background-color: rgb(150, 71, 150)\n"
"}\n"
"\n"
"QPushButton#add_token {\n"
"    height: 20px;\n"
"    \n"
"    font: 12pt \"Myanmar Text\";\n"
"    background-color: rgb(0, 255, 191);\n"
"    border: white;\n"
"    border-radius: 5px\n"
"}\n"
"\n"
"QPushButton#add_token::hover {\n"
"    background-color: rgb(0, 240, 176)    \n"
"}\n"
"\n"
"QPushButton#add_token::pressed {\n"
"    background-color: rgb(0, 234, 172)\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.tabWidget = QtWidgets.QTabWidget(self.frame)
        self.tabWidget.setGeometry(QtCore.QRect(0, 120, 411, 301))
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tabWidget.setObjectName("tabWidget")
        self.transaction = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.transaction.sizePolicy().hasHeightForWidth())
        self.transaction.setSizePolicy(sizePolicy)
        self.transaction.setBaseSize(QtCore.QSize(44, 0))
        self.transaction.setObjectName("transaction")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.transaction)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.transaction)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 385, 248))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayoutScrool = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.transaction, "")
        self.tokens = QtWidgets.QWidget()
        self.tokens.setObjectName("tokens")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tokens)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.add_token = QtWidgets.QPushButton(self.tokens)
        self.add_token.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_token.setObjectName("add_token")
        self.verticalLayout_2.addWidget(self.add_token)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tokens)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 385, 249))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayoutScrool2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.addWidget(self.scrollArea_2)
        self.tabWidget.addTab(self.tokens, "")
        self.account_options = QtWidgets.QFrame(self.frame)
        self.account_options.setGeometry(QtCore.QRect(-1, -1, 411, 111))
        self.account_options.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.account_options.setFrameShadow(QtWidgets.QFrame.Raised)
        self.account_options.setObjectName("account_options")
        self.gridLayout = QtWidgets.QGridLayout(self.account_options)
        self.gridLayout.setObjectName("gridLayout")
        self.accounts = QtWidgets.QComboBox(self.account_options)
        self.accounts.setObjectName("accounts")
        self.gridLayout.addWidget(self.accounts, 0, 0, 1, 1)
        self._import = QtWidgets.QPushButton(self.account_options)
        self._import.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self._import.setObjectName("_import")
        self.gridLayout.addWidget(self._import, 0, 2, 1, 1)
        self.account_address = QtWidgets.QLabel(self.account_options)
        self.account_address.setObjectName("account_address")
        self.gridLayout.addWidget(self.account_address, 1, 0, 1, 1)
        self.create = QtWidgets.QPushButton(self.account_options)
        self.create.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.create.setObjectName("create")
        self.gridLayout.addWidget(self.create, 1, 2, 1, 1)
        self.balance = QtWidgets.QLabel(self.account_options)
        self.balance.setObjectName("balance")
        self.gridLayout.addWidget(self.balance, 2, 0, 1, 1)
        self.send = QtWidgets.QPushButton(self.account_options)
        self.send.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.send.setObjectName("send")
        self.gridLayout.addWidget(self.send, 2, 2, 1, 1)
        self.copy = QtWidgets.QPushButton(self.account_options)
        self.copy.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.copy.setToolTip("")
        self.copy.setStatusTip("")
        self.copy.setWhatsThis("")
        self.copy.setAccessibleName("")
        self.copy.setAccessibleDescription("")
        self.copy.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("graphic/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.copy.setIcon(icon)
        self.copy.setObjectName("copy")
        self.gridLayout.addWidget(self.copy, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi()
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(self)
        self.setTabOrder(self._import, self.create)
        self.setTabOrder(self.create, self.send)
        self.setTabOrder(self.send, self.tabWidget)
        self.setTabOrder(self.tabWidget, self.copy)
        self.setTabOrder(self.copy, self.scrollArea)
        self.setTabOrder(self.scrollArea, self.scrollArea_2)
    
    def addTx(self, _tx_index, _tx_hash, _date, _amount):
        styleI = 'font: 75 14pt "Nirmala UI"; color: white'
        styleII = 'font: 75 italic 11pt "Verdana";color: rgb(212, 212, 212)'
        gridLayout = QtWidgets.QGridLayout()
        tx_index = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        tx_index.setText(_tx_index)
        tx_index.setStyleSheet(styleI)
        gridLayout.addWidget(tx_index, 0, 0, 2, 1)

        tx_hash = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        tx_hash.setSizePolicy(
            QtWidgets.QSizePolicy.Ignored, 
            QtWidgets.QSizePolicy.Ignored
            )
        tx_hash.setText(_tx_hash)
        tx_hash.setStyleSheet(styleII)
        gridLayout.addWidget(tx_hash, 0, 1, 1, 1)
        
        date = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        date.setText(_date)
        date.setStyleSheet(styleII)
        gridLayout.addWidget(date, 1, 1, 1, 1)

        amount = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        amount.setText(_amount + 'ETH')
        amount.setStyleSheet(styleI)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        amount.setFont(font)
        gridLayout.addWidget(amount, 0, 2, 2, 1)

        self.verticalLayoutScrool.addLayout(gridLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
    
    def addToken(self, _name, symbol, _address, _balance, _excute):
        styleI = 'font: 75 14pt "Nirmala UI"; color: white'
        styleII = 'font: 75 italic 11pt "Verdana";color: rgb(212, 212, 212)'
        styleIII = """
        #excute {
           background-color: transparent;
            color: white;
            border: 3px solid white;
            border-radius: 5px
         }
        #excute::hover {
           border: 2px solid white;
            border-radius: 6px
         }
        """
        gridLayout = QtWidgets.QGridLayout()
        
        balance = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        balance.setObjectName("balance")
        balance.setText(_balance)
        balance.setStyleSheet(styleI)
        gridLayout.addWidget(balance, 0, 0, 2, 1)

        address = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        address.setObjectName("address")
        address.setSizePolicy(
            QtWidgets.QSizePolicy.Ignored, 
            QtWidgets.QSizePolicy.Ignored
            )
        address.setText(_address)
        address.setStyleSheet(styleII)
        gridLayout.addWidget(address, 0, 1, 1, 2)

        name = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        name.setObjectName("name")
        name.setText(_name)
        name.setStyleSheet(styleII)
        gridLayout.addWidget(name, 1, 1, 1, 2)
        
        excuter = _excute
        excuter.resize(40, 30)
        excuter.setProperty('balance', balance)
        excuter.setObjectName("excute")
        excuter.setText('Execute')
        excuter.setStyleSheet(styleIII)
        gridLayout.addWidget(excuter, 0, 3, 2, 1)

        self.verticalLayoutScrool2.addLayout(gridLayout)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        
    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("main", "main"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.transaction), _translate("main", "transaction"))
        self.add_token.setText(_translate("main", "+ Add Token"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tokens), _translate("main", "Tokens"))
        self._import.setText(_translate("main", "import"))
        self.account_address.setText(_translate("main", "address"))
        self.create.setText(_translate("main", "create"))
        self.balance.setText(_translate("main", "balance"))
        self.send.setText(_translate("main", "Send"))
