# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RestoreVault.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class RestoreVault(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.setupUi()

    def setupUi(self):
        self.setObjectName("restoreVault")
        self.resize(400, 431)
        self.horizontalLayout = QtWidgets.QHBoxLayout(self)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self)
        self.frame.setStyleSheet("#title {\n"
"    color: rgb(6, 255, 118)\n"
"}\n"
"\n"
"#title::hover {\n"
"    color: rgb(5, 229, 102)\n"
"}\n"
"\n"
"#seedLabel {\n"
"    color: white\n"
"}\n"
"\n"
"#seedLabel::hover {\n"
"    color: rgb(223, 223, 223)\n"
"}\n"
"\n"
"#seed {\n"
"    color: white;\n"
"    background-color: transparent;\n"
"    border: 3px solid white;\n"
"    border-radius: 5px\n"
"}\n"
"\n"
"#seed::focus {\n"
"    border-color: #CA8ACA;\n"
"    background-color: rgba(171, 81, 171, 100)\n"
"}\n"
"\n"
"#password, #pwd_conf {\n"
"    color: white;\n"
"    background-color: transparent;\n"
"    border: 3px solid white;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"#password::focus, #conf_pwd::focus {\n"
"    border-color: rgb(202, 138, 202);\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: rgb(168, 80, 168);\n"
"    color: white;\n"
"    height: 30px;\n"
"    border: 3px soild white;\n"
"    border-radius: 5px;\n"
"    \n"
"    font: 75 12pt \"Verdana\";\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    border: 2px solid white;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color: rgb(148, 70, 148)\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.title = QtWidgets.QLabel(self.frame)
        self.title.setGeometry(QtCore.QRect(110, 10, 181, 31))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(18)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.seedLabel = QtWidgets.QLabel(self.frame)
        self.seedLabel.setGeometry(QtCore.QRect(20, 60, 151, 21))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(18)
        self.seedLabel.setFont(font)
        self.seedLabel.setObjectName("seedLabel")
        self.seed = QtWidgets.QPlainTextEdit(self.frame)
        self.seed.setGeometry(QtCore.QRect(5, 91, 371, 191))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.seed.setFont(font)
        self.seed.setObjectName("seed")
        self.password = QtWidgets.QLineEdit(self.frame)
        self.password.setGeometry(QtCore.QRect(10, 290, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        self.password.setFont(font)
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.pwd_conf = QtWidgets.QLineEdit(self.frame)
        self.pwd_conf.setGeometry(QtCore.QRect(10, 330, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        self.pwd_conf.setFont(font)
        self.pwd_conf.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pwd_conf.setObjectName("pwd_conf")
        self.back = QtWidgets.QPushButton(self.frame)
        self.back.setGeometry(QtCore.QRect(0, 0, 51, 31))
        self.back.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("graphic/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back.setIcon(icon)
        self.back.setIconSize(QtCore.QSize(30, 30))
        self.back.setObjectName("pushButton")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(207, 370, 161, 41))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.restore = QtWidgets.QPushButton(self.widget)
        self.restore.setObjectName("restore")
        self.horizontalLayout_2.addWidget(self.restore)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("restoreVault", "restoreVault"))
        self.title.setText(_translate("restoreVault", "Restore Vault"))
        self.seedLabel.setText(_translate("restoreVault", "Wallet Seed"))
        self.seed.setPlaceholderText(_translate("restoreVault", "Enter your secret twelece word phrase here to restore your vault."))
        self.password.setPlaceholderText(_translate("restoreVault", "New Password (min 8 chars)"))
        self.pwd_conf.setPlaceholderText(_translate("restoreVault", "Confirm Password"))
        self.restore.setText(_translate("restoreVault", "Restore"))
