# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Seed.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Seed(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.setupUi()

    def setupUi(self):
        self.setObjectName("Seed")
        self.resize(431, 427)
        self.horizontalLayout = QtWidgets.QHBoxLayout(self)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self)
        self.widget.setStyleSheet("#title {\n"
"    color: white;\n"
"}\n"
"\n"
"#title::hover {\n"
"    color: rgb(226, 226, 226)\n"
"}\n"
"\n"
"#warning {\n"
"    background-color: rgba(255, 56, 59, 50);\n"
"    color: rgba(255, 0, 0, 150);\n"
"    border: 3px solid rgba(255, 0, 0, 200);\n"
"    border-radius: 5px\n"
"}\n"
"\n"
"#seed {\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    font: 75 12pt \"Orbitron\";\n"
"    border: 3px solid white;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"#seed::hover {\n"
"    border-color: #CA8ACA;\n"
"    background-color: rgba(214, 146, 214, 50)\n"
"}\n"
"\n"
"#next {\n"
"    background-color: rgb(2, 255, 150);\n"
"    font: 75 12pt \"Orbitron\";\n"
"    color: white;\n"
"    border: 3px solid white;\n"
"    border-radius: 5px\n"
"}\n"
"\n"
"#next::hover {\n"
"    border: 2px solid white;\n"
"    border-radius: 6px\n"
"}\n"
"\n"
"#next::pressed {\n"
"    background-color: rgb(1, 221, 130)\n"
"}")
        self.widget.setObjectName("widget")
        self.warning = QtWidgets.QLabel(self.widget)
        self.warning.setGeometry(QtCore.QRect(40, 60, 331, 71))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.warning.setFont(font)
        self.warning.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.warning.setTextFormat(QtCore.Qt.PlainText)
        self.warning.setScaledContents(True)
        self.warning.setWordWrap(True)
        self.warning.setObjectName("warning")
        self.title = QtWidgets.QLabel(self.widget)
        self.title.setGeometry(QtCore.QRect(100, 10, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setWordWrap(False)
        self.title.setObjectName("title")
        self.seed = QtWidgets.QPlainTextEdit(self.widget)
        self.seed.setEnabled(True)
        self.seed.setGeometry(QtCore.QRect(23, 160, 371, 151))
        self.seed.setReadOnly(True)
        self.seed.setPlainText("")
        self.seed.setObjectName("seed")
        self.next = QtWidgets.QPushButton(self.widget)
        self.next.setGeometry(QtCore.QRect(54, 342, 301, 31))
        self.next.setObjectName("next")
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Seed", "Seed"))
        self.warning.setText(_translate("Seed", "These 12 words are the only way to restore your Zahir Wallet accounts. Save them somewhere safe and secret."))
        self.title.setText(_translate("Seed", "Vault Created"))
        self.next.setText(_translate("Seed", "I\'ve copied it somewhere safe"))
