# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'singUp.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class SingUp(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.setupUi()

    def setupUi(self):
        self.setObjectName("singUp")
        self.resize(427, 431)
        self.horizontalLayout = QtWidgets.QHBoxLayout(self)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self)
        self.frame.setStyleSheet("QLabel#appName {\n"
"    background-color: transparent;\n"
"    color: black;\n"
"    font: 75 20pt \"Nirmala UI\";\n"
"}\n"
"\n"
"QLabel#appName::hover {\n"
"    color: rgb(53, 53, 53)\n"
"}\n"
"\n"
"QLineEdit{\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    border: 3px solid white;\n"
"    border-radius: 5px\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border-color: #CA8ACA\n"
"}\n"
"\n"
"QPushButton#create {\n"
"    color: white;\n"
"    border: 3px solid #592859;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton#create::pressed {\n"
"    border-color: rgb(124, 56, 124);\n"
"    background-color: rgb(145, 69, 145);\n"
"    padding-top: 10px;\n"
"    padding-left: 10px\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.appLogo = QtWidgets.QLabel(self.frame)
        self.appLogo.setGeometry(QtCore.QRect(120, 10, 191, 101))
        self.appLogo.setText("")
        self.appLogo.setPixmap(QtGui.QPixmap("graphic/logo.png"))
        self.appLogo.setScaledContents(True)
        self.appLogo.setObjectName("appLogo")
        self.password = QtWidgets.QLineEdit(self.frame)
        self.password.setGeometry(QtCore.QRect(20, 190, 371, 41))
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(17)
        self.password.setFont(font)
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.password_conf = QtWidgets.QLineEdit(self.frame)
        self.password_conf.setGeometry(QtCore.QRect(20, 240, 371, 41))
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(17)
        self.password_conf.setFont(font)
        self.password_conf.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_conf.setObjectName("password_conf")
        self.create = QtWidgets.QPushButton(self.frame)
        self.create.setGeometry(QtCore.QRect(110, 320, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.create.setFont(font)
        self.create.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.create.setObjectName("create")
        self.appName = QtWidgets.QLabel(self.frame)
        self.appName.setGeometry(QtCore.QRect(140, 110, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.appName.setFont(font)
        self.appName.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.appName.setObjectName("appName")
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("singUp", "singUp"))
        self.password.setPlaceholderText(_translate("singUp", "New Password (min 8 chars)"))
        self.password_conf.setPlaceholderText(_translate("singUp", "Confirm Password"))
        self.create.setText(_translate("singUp", "Create"))
        self.appName.setText(_translate("singUp", "Zahir Wallet"))
