# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'titleBar.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class titleBar(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.setupUi()
        
    def setupUi(self):
        self.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        self.setObjectName('title')
        self.resize(430, 499)
        self.contanier = QtWidgets.QStackedWidget(self)
        self.contanier.setGeometry(QtCore.QRect(0, 70, 431, 431))
        self.contanier.setStyleSheet("QWidget {\n"
"    background-color: #B154B1;\n"
"}")
        self.contanier.setObjectName("contanier")
        self.titleBar = QtWidgets.QFrame(self)
        self.titleBar.setGeometry(QtCore.QRect(0, 0, 431, 71))
        self.titleBar.setStyleSheet("QFrame#titleBar {\n"
"    border-bottom: 3px solid white;\n"
"    background-color: rgb(161, 76, 161);\n"
"}\n"
"QLabel#logo {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QLabel#title {\n"
"    background-color: transparent;\n"
"    color: black;\n"
"    font: 75 20pt \"Nirmala UI\";\n"
"}\n"
"\n"
"QLabel#title::hover{\n"
"    color: rgb(53, 53, 53)\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color:  rgb(161, 76, 161);\n"
"    border: 4px solid white;\n"
"    border-left: 0;\n"
"    border-top: 0;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"#close {\n"
"    color: red;\n"
"}\n"
"\n"
"#minimize {\n"
"    color: green;\n"
"}\n"
"#minimize::pressed, #close::pressed, #provider::pressed {\n"
"    background-color: rgb(149, 70, 149);\n"
"    border: 4px solid rgb(229, 229, 229);\n"
"    border-bottom: 0;\n"
"    border-right: 0\n"
"}\n"
"")
        self.titleBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.titleBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titleBar.setObjectName("titleBar")
        self.title = QtWidgets.QLabel(self.titleBar)
        self.title.setGeometry(QtCore.QRect(70, 20, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.logo = QtWidgets.QLabel(self.titleBar)
        self.logo.setGeometry(QtCore.QRect(-30, 0, 141, 71))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("graphic/logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.layoutWidget = QtWidgets.QWidget(self.titleBar)
        self.layoutWidget.setGeometry(QtCore.QRect(290, 10, 131, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        
        self.provider = QtWidgets.QPushButton(self.layoutWidget)
        self.provider.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("graphic/provider.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.provider.setIcon(icon)
        self.provider.setIconSize(QtCore.QSize(40, 40))
        self.provider.setObjectName("provider")
        self.horizontalLayout_2.addWidget(self.provider)
        self.provider.hide()

        self.minimize = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Permanent Marker")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.minimize.setFont(font)
        self.minimize.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minimize.setObjectName("minimize")
        self.horizontalLayout_2.addWidget(self.minimize)
        self.close = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Permanent Marker")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.close.setFont(font)
        self.close.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.close.setObjectName("close")
        self.horizontalLayout_2.addWidget(self.close)

        self.copy_icon_label = QtWidgets.QLabel(self)
        self.copy_icon = QtGui.QPixmap('graphic/copy.png')
        self.copy_icon_label.setPixmap(self.copy_icon)
        self.copy_icon_label.resize(50, 50)
        self.copy_icon_label.setPixmap(
                self.copy_icon.scaled(
                    self.copy_icon_label.size(), QtCore.Qt.KeepAspectRatio, QtCore.Qt.SmoothTransformation
                    )
                )
        self.copy_icon_label.move(180, 350)
        self.copy_icon_label.hide()

        self.loading_label = QtWidgets.QLabel(self)
        self.loading = QtGui.QMovie('graphic/loading.gif')
        self.loading_label.setMovie(self.loading)
        self.loading_label.move(165, 179)
        self.loading_label.hide()
        self.loading.start()

        self.frame = QtWidgets.QFrame(self)
        self.frame.resize(300, 200)
        self.frame.move(80, 200)
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: #B154B1;\n"
"   border: 3px solid white;\n"
"   border-radius: 10px;\n"
"}\n"
"\n"
"QLabel {\n"
"    border: 0;\n"
"    color: white;\n"
"}\n"
"\n"
"QLabel::hover {\n"
"    color: rgb(213, 213, 213)\n"
"}\n"
"\n"
"QComboBox {\n"
"    color: white;\n"
"    background-color: transparent;\n"
"    border: 3px solid white;\n"
"    border-radius: 5px\n"
"}\n"
"\n"
"QComboBox::focus {\n"
"    border: 2px solid rgb(150, 71, 150);\n"
"    border-radius: 6px\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: rgb(211, 100, 211);\n"
"    border: 3px solid white;\n"
"    font: 75 11pt \"Nirmala UI\";\n"
"    color: white;\n"
"    border-radius: 5px\n"
"}\n"
"\n"
"QPushButton::hover {background-color: rgb(204, 97, 204)}\n"
"QPushButton::pressed {\n"
"    border: 2px solid rgb(238, 238, 238);\n"
"    border-radius: 5px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.RPCUrl = QtWidgets.QComboBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(13)
        self.RPCUrl.setFont(font)
        self.RPCUrl.setEditable(True)
        self.RPCUrl.setObjectName("comboBox")
        self.verticalLayout.addWidget(self.RPCUrl)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cancel = QtWidgets.QPushButton(self.frame)
        self.cancel.setMinimumSize(QtCore.QSize(0, 30))
        self.cancel.setMaximumSize(QtCore.QSize(1010212, 16777215))
        self.cancel.setObjectName("cancel")
        self.horizontalLayout_2.addWidget(self.cancel)
        self.save = QtWidgets.QPushButton(self.frame)
        self.save.setMinimumSize(QtCore.QSize(0, 30))
        self.save.setMaximumSize(QtCore.QSize(1010212, 16777215))
        self.save.setObjectName("save")
        self.horizontalLayout_2.addWidget(self.save)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.frame.hide()

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate('title', 'title'))
        self.title.setText(_translate('title', "ZahirWallet"))
        self.minimize.setText(_translate('title', "_"))
        self.close.setText(_translate('title', "X"))
        self.label.setText(_translate("title", "Add  RPC"))
        self.RPCUrl.setCurrentText(_translate("title", "New RPC URL."))
        self.cancel.setText(_translate("title", "Cancel"))
        self.save.setText(_translate("title", "Save"))


if __name__ == '__main__':
    import sys
    app = QtWidgets.QApplication(sys.argv)
    title = titleBar()
    title.show()
    sys.exit(app.exec_())
